import axios from "axios";

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN1ZXZhc2dpbGJlcnRvMTE4QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhZG9yIiwibG9jYXRpb25zIjpbeyJpZCI6MSwibmFtZSI6Iktha3V5byIsImNvZGUiOiIwMDEifSx7ImlkIjoyLCJuYW1lIjoiU2FudGEgTGF1cmEiLCJjb2RlIjoiMDAyIn1dLCJjb21wYW55Ijp7ImlkIjoxLCJjb2RlIjoiMDAxIiwibmFtZSI6IlZpbGVvc29mdCJ9LCJzZWFzb24iOnsiaWQiOjEyLCJjb2RlIjoiMDAyIiwibmFtZSI6IlZFUi0yMDI0Iiwic3RhcnREYXRlIjoiMjAyMy0wOS0xMFQwNzowMDowMC4wMDBaIiwiZW5kRGF0ZSI6IjIwMjMtMDktMjBUMDc6MDA6MDAuMDAwWiIsIm9wZW4iOnRydWUsImlzQWN0aXZlIjp0cnVlfSwiZGF0ZSI6IjIwMjMtMDktMTZUMDE6MjA6MDMuMzQyWiIsInVzZXIiOnsiaWQiOjgsImNvZGUiOiIwMDEiLCJuYW1lIjoiR2lsYmVydG8iLCJsYXN0TmFtZSI6IkN1ZXZhcyIsImVtYWlsIjoiY3VldmFzZ2lsYmVydG8xMThAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkV1JIeHgvNTJjUXFkcDBpRE9qTC5IT2xMTGwyMXNkMlV5ZlVWOGZPajY3Vmo3N2N1cTV3LnUiLCJpc0FjdGl2ZSI6dHJ1ZSwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJsb2NhdGlvbnMiOlt7ImlkIjoxLCJuYW1lIjoiS2FrdXlvIiwiY29kZSI6IjAwMSJ9LHsiaWQiOjIsIm5hbWUiOiJTYW50YSBMYXVyYSIsImNvZGUiOiIwMDIifV0sImNvbXBhbnkiOnsiaWQiOjEsImNvZGUiOiIwMDEiLCJuYW1lIjoiVmlsZW9zb2Z0In19LCJpYXQiOjE2OTQ4MjcyMDN9.Gdsv9mOzLjBkL-vUc6LajlamESyOpgF114s_kO4wTHk"

const axiosClient = axios.create({
    baseURL: import.meta.env.VITE_API_URL,
    headers: {
        Authorization: `Bearer ${token}`
    }
});

export default axiosClient;